# Generated by Django 4.1.7 on 2023-03-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_customer_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.customer')),
            ],
        ),
    ]
