# Generated by Django 4.1.7 on 2023-03-01 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '996*********'. Up to 12 digits allowed.", regex='^996\\d{9}$')]),
        ),
    ]
