# Generated by Django 4.1.7 on 2023-03-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_customer_author_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='author',
        ),
    ]
